### ISSUE TITLE
update senses30.src

### ISSUE THREAD

**Issue by rafaelbetatester** [own-pt/FreeLing#5]
<a href="https://github.com/arademaker"><img src="https://avatars.githubusercontent.com/u/86403?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arademaker](https://github.com/arademaker)**
_Monday Feb 22, 2016 at 11:23 GMT_
_Originally opened as https://github.com/own-pt/freeling_pt/issues/3_

----

with the last openWordnet-PT release.

**Comment by arademaker** [comment]
done e já aceito pelo Padro.
